In [1]:
import numpy as np
import sympy as sym
sym.init_printing()

---
# Higher Powers of a Stochastic Matrix

---

In [2]:
nVec = np.array([3, 5, 10, 100, 1000])
A = np.array([[.9, .5],[.1, .5]])
for n in nVec:
    # Function that computes A^n in a more efficient and accurate way
    An = np.linalg.matrix_power(A,n)
    print("n = " + str(n))
    print(An)
    print("")

n = 3
[[0.844 0.78 ]
 [0.156 0.22 ]]

n = 5
[[0.83504 0.8248 ]
 [0.16496 0.1752 ]]

n = 10
[[0.83335081 0.83324595]
 [0.16664919 0.16675405]]

n = 100
[[0.83333333 0.83333333]
 [0.16666667 0.16666667]]

n = 1000
[[0.83333333 0.83333333]
 [0.16666667 0.16666667]]



---
# Eigenvalues of $A^n$ (Positive Stochastic)

---

In [3]:
# Lets look at the eigenvalues of A
D,V = np.linalg.eig(A)
print(V) # Print out the eigenvectors
print(D) # Print out the eigenvalues
# Convert the eigenvalue array into a diagonal matrix
D = np.diag(D)

[[ 0.98058068 -0.70710678]
 [ 0.19611614  0.70710678]]
[1.  0.4]


In [4]:
for n in range(1,5):
    Dn = np.linalg.matrix_power(D,n)
    print("n = " + str(n))
    print(Dn)
    print("")

n = 1
[[1.  0. ]
 [0.  0.4]]

n = 2
[[1.   0.  ]
 [0.   0.16]]

n = 3
[[1.    0.   ]
 [0.    0.064]]

n = 4
[[1.     0.    ]
 [0.     0.0256]]



In [5]:
for n in range(5,10):
    Dn = np.linalg.matrix_power(D,n)
    print("n = " + str(n))
    print(Dn)
    print("")

n = 5
[[1.      0.     ]
 [0.      0.01024]]

n = 6
[[1.       0.      ]
 [0.       0.004096]]

n = 7
[[1.        0.       ]
 [0.        0.0016384]]

n = 8
[[1.0000e+00 0.0000e+00]
 [0.0000e+00 6.5536e-04]]

n = 9
[[1.00000e+00 0.00000e+00]
 [0.00000e+00 2.62144e-04]]



In [6]:
for n in nVec:
    # Function that computes A^n in a more efficient and accurate way
    Dn = np.linalg.matrix_power(D,n)
    print("n = " + str(n))
    print(Dn)
    print("")

n = 3
[[1.    0.   ]
 [0.    0.064]]

n = 5
[[1.      0.     ]
 [0.      0.01024]]

n = 10
[[1.000000e+00 0.000000e+00]
 [0.000000e+00 1.048576e-04]]

n = 100
[[1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.60693804e-40]]

n = 1000
[[1. 0.]
 [0. 0.]]



---
# Steady State Solution

---

In [7]:
A = np.array([
    [.3, .4, .5],
    [.3, .4, .3],
    [.4, .2, .2]])
D,V = np.linalg.eig(A)

In [8]:
print(D) # Prints out the eigenvalues so we know which vector to grab

[ 1.  -0.2  0.1]


In [9]:
v = V[0:3,0] # This is the eigenvector associated with 1
print(v)
w = v/sum(v) # This makes it the steady state
print(w)

[-0.66742381 -0.57207755 -0.47673129]
[0.38888889 0.33333333 0.27777778]
